services:
  api:
    volumes:
      - static_volume:/app/staticfiles
    command: >
      gunicorn library.wsgi:application
      --bind 0.0.0.0:8000
      --workers 3
      --timeout 120
    ports:
      - "8000:8000"
    environment:
      DEBUG: "0"
      # DJANGO_SETTINGS_MODULE: library.settings.prod
    restart: always